DEFINE A.APPEND &1 TO A. END-OF-DEFINITION.
REPORT.DATA:A TYPE TABLE OF STRING,B(8).
A`REPORT.FORM F TABLES T.`.
A`WRITE /'DEFINE A.APPEND &1 TO A. END-OF-DEFINITION.'.`.
A`WRITE /'REPORT.DATA:A TYPE TABLE OF STRING,B(8).'.`.
A`LOOP AT T.REPLACE ALL OCCURENCES OF'``' IN T`.
A`WITH'````'.WRITE:/'A``' NO-GAP,T NO-GAP, '``.' NO-GAP.`.
A`ENDLOOP.WRITE /'GENERATE SUBROUTINE POOL A NAME B.PERFORM F'.`.
A`WRITE /'IN PROGRAM (B) TABLES A.'.ENDFORM.`.
GENERATE SUBROUTINE POOL A NAME B.PERFORM F
IN PROGRAM (B) TABLES A.
